import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'
import * as path from 'path'
import * as fs from 'fs'

// Load environment variables
dotenv.config({ path: path.join(__dirname, '../.env.local') })

async function updateToLocalImages() {
  console.log('🔄 Updating vehicle images to local paths...\n')

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY

  if (!supabaseUrl || !supabaseKey) {
    console.error('❌ Missing Supabase credentials')
    process.exit(1)
  }

  const supabase = createClient(supabaseUrl, supabaseKey)

  // Read the image mapping generated by download-images.ts
  const mappingFile = path.join(__dirname, 'image-mapping.json')
  const imageMapping: Record<string, string[]> = JSON.parse(fs.readFileSync(mappingFile, 'utf-8'))

  try {
    // Fetch all vehicles
    console.log('📊 Fetching vehicles from database...')
    const { data: vehicles, error: fetchError } = await supabase
      .from('vehicles')
      .select('*')
      .order('created_at', { ascending: false })

    if (fetchError) {
      console.error('❌ Error fetching vehicles:', fetchError.message)
      process.exit(1)
    }

    if (!vehicles || vehicles.length === 0) {
      console.log('ℹ️  No vehicles found in database')
      return
    }

    console.log(`Found ${vehicles.length} vehicles\n`)

    let updatedCount = 0
    let skippedCount = 0

    // Update each vehicle with local image paths
    for (const vehicle of vehicles) {
      const vehicleKey = `${vehicle.make} ${vehicle.model}`
      const localImages = imageMapping[vehicleKey]

      if (localImages && localImages.length > 0) {
        console.log(`🖼️  Updating ${vehicleKey}...`)
        console.log(`   Replacing ${vehicle.images?.length || 0} remote URLs with ${localImages.length} local paths`)

        const { error: updateError } = await supabase
          .from('vehicles')
          .update({ images: localImages })
          .eq('id', vehicle.id)

        if (updateError) {
          console.error(`   ❌ Error updating ${vehicleKey}:`, updateError.message)
        } else {
          console.log(`   ✅ Updated successfully`)
          updatedCount++
        }
      } else {
        console.log(`⏭️  Skipping ${vehicleKey} - no local images found`)
        skippedCount++
      }
    }

    console.log('\n' + '='.repeat(60))
    console.log(`✅ Local image update complete!`)
    console.log(`   Updated: ${updatedCount} vehicles`)
    console.log(`   Skipped: ${skippedCount} vehicles`)
    console.log('='.repeat(60))

  } catch (err) {
    console.error('❌ Unexpected error:', err)
    process.exit(1)
  }
}

updateToLocalImages()
